"""Asset models for the AI Agency system."""

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class CustomerPersona(BaseModel):
    """Customer persona generated by Strategy Agent."""

    name: str
    age_range: str
    description: str
    pain_points: List[str]
    motivations: List[str]
    product_usage_context: str


class ImageAsset(BaseModel):
    """Image asset generated by Art Director Agent."""

    asset_id: str
    url: str
    generation_params: dict
    description: str

    # Refinement tracking (within same generation)
    parent_asset_id: Optional[str] = None  # If this is a refinement of another image
    refinement_iteration: int = 0  # 0 = original, 1+ = refinement version
    user_feedback_applied: Optional[str] = None  # Feedback that led to this version

    # Generation tracking (NEW - production level)
    generation_number: int = 1  # Which generation batch (1, 2, 3...)
    variation_number: int = 1   # Which variation within generation (1, 2, 3, 4)


class ImageRefinementRequest(BaseModel):
    """User request to refine a specific image."""

    image_asset_id: str  # ID of image to refine
    feedback: str  # Natural language feedback (e.g., "add modern elements")
    variation_number: int  # Which variation (1-4)


class ImageRefinementHistory(BaseModel):
    """Track refinement iterations for an image."""

    original_asset_id: str
    refinements: List[ImageAsset] = []
    feedback_history: List[str] = []
    iteration_count: int = 0


class GenerationSnapshot(BaseModel):
    """Snapshot of a complete generation of hero images (NEW - production level)."""

    generation_number: int
    created_at: datetime
    images: List[ImageAsset]  # The 4 images from this generation
    theme: str
    reason: str  # "initial", "regenerated with darker theme", etc.
    slogan: Optional[str] = None  # Slogan used for this generation

    class Config:
        """Pydantic configuration."""

        json_encoders = {datetime: lambda v: v.isoformat()}


class VideoAsset(BaseModel):
    """Video asset generated by Video Producer Agent."""

    asset_id: str
    url: str
    duration_seconds: float
    generation_params: dict
    revision_number: int = 0


class AudioAsset(BaseModel):
    """Audio asset generated by Audio Team Agent."""

    asset_id: str
    url: str
    duration_seconds: float
    audio_type: str  # "jingle", "podcast_ad"
    script: Optional[str] = None  # Ad script for podcast_ad type


class TranscriptionAsset(BaseModel):
    """Transcription asset generated by Chirp."""

    asset_id: str
    text: str
    language: str
    format: str  # "srt", "vtt", "txt"


class CodeAsset(BaseModel):
    """Code asset generated by Web Dev Agent."""

    asset_id: str
    html: str
    css: str
    javascript: str
    preview_url: Optional[str] = None


# Agent Output Models


class StrategyAgentOutput(BaseModel):
    """Output from Strategy Agent."""

    personas: List[CustomerPersona] = Field(..., min_length=3, max_length=3)
    slogans: List[str] = Field(..., min_length=5, max_length=5)
    market_analysis: str
    visual_theme_extracted: str
    category_insights: str


class ArtDirectorOutput(BaseModel):
    """Output from Art Director Agent."""

    images: List[ImageAsset] = Field(..., min_length=4, max_length=4)
    style_guide: str


class VideoProducerOutput(BaseModel):
    """Output from Video Producer Agent."""

    video: VideoAsset
    critique_notes: Optional[str] = None
    revision_history: List[str] = []


class AudioTeamOutput(BaseModel):
    """Output from Audio Team Agent."""

    jingle: AudioAsset
    podcast_ad: AudioAsset
    transcription: TranscriptionAsset
    proactive_suggestion: Optional[str] = None


class WebDevOutput(BaseModel):
    """Output from Web Dev Agent."""

    code: CodeAsset
    framework: str = "vanilla"
    deployment_status: str = "preview"


# Critique System Models


class CritiqueResult(BaseModel):
    """Result from Producer's critique system."""

    status: str  # "PASS" or "REVISE"
    score: float  # 0.0 to 1.0
    issues: List[str] = []
    revision_instructions: Optional[str] = None


# Campaign Plan Models


class PlanPhase(BaseModel):
    """Single phase in campaign execution plan."""

    phase_number: int
    agent: str
    task_description: str
    dependencies: List[int] = []


class CampaignPlan(BaseModel):
    """5-phase campaign execution plan."""

    phases: List[PlanPhase]
    approval_status: str = "pending"  # pending, approved, rejected
    description: str = ""


# Campaign Template Model


class CampaignTemplate(BaseModel):
    """Product-agnostic campaign template."""

    product_name: str
    product_category: str
    theme: str
    key_features: List[str]
    target_market: str
    initial_sketch_url: str
    brand_tone: str
